version: '3.7'
services:
  app:
    build:
      args:
        user: aulaSQL
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app-php
    container_name: app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - web-net
      - db-net
  
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web-net

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: aulaSQL
      MARIADB_USER: aulaSQL
      MARIADB_PASSWORD: pass
    networks:
      - db-net


networks:
  web-net:
  db-net: